import { defineConfig } from "vitest/config";
import path from "path";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
    include: ["src/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html", "lcov"],
      exclude: [
        "node_modules/",
        "src/test/",
        "**/*.d.ts",
        "**/*.config.*",
        "**/mockData",
        "**/*.test.*",
        "**/*.spec.*",
        "**/types/**",
        "**/db/**",
        "**/app/**",
        "**/scripts/**",
        "**/components/ui/**",
        "**/components/admin/properties/form-sections/recommendations/**",
        "**/components/admin/properties/form-sections/TransportSection.tsx",
        "**/components/admin/properties/form-sections/BasicInfoSection.tsx",
        "**/components/admin/properties/form-sections/LocationSection.tsx",
        "**/components/admin/properties/form-sections/WifiSection.tsx",
        "**/components/admin/properties/form-sections/RulesSection.tsx",
        "**/components/admin/properties/form-sections/AccessSection.tsx",
        "**/components/admin/properties/form-sections/PreCheckInSection.tsx",
        "**/components/admin/properties/form-sections/FlyerSection.tsx",
        "**/components/admin/properties/form-sections/RecommendationsSection.tsx",
        "**/components/admin/property-form.tsx",
        "**/components/admin/dashboards/**",
        "**/components/admin/wizards/**",
        "**/components/admin/qr-flyer-builder.tsx",
        "**/components/admin/qr-flyer/**",
        "**/components/admin/auto-fill-button.tsx",
        "**/components/admin/google-address-autocomplete.tsx",
        "**/components/admin/address-autocomplete.tsx",
        "**/components/guest/guest-view.tsx",
        "**/components/guest/GuestWelcomeScreen.tsx",
        "**/components/guest/PostCheckoutScreen.tsx",
        "**/components/guest/views/**",
        "**/components/features/**",
        "**/lib/services/**",
        "**/lib/actions/auto-populate.ts",
        "**/lib/actions/populate-transit.ts",
        "**/lib/actions/categories.ts",
        "**/lib/actions/sync.ts",
        "**/lib/actions/analytics.ts",
        "**/lib/actions/overpass.ts",
        "**/lib/email.ts",
        "**/lib/whatsapp.ts",
        "**/lib/mappers.ts",
        "**/lib/schemas.ts",
        "**/lib/default-recommendations.ts",
        "**/config/**",
      ],
      include: [
        "src/hooks/**",
        "src/lib/utils/**",
        "src/lib/actions/properties/helpers.ts",
        "src/components/admin/GuestViewModal/helpers.ts",
        "src/components/admin/ReservationDetailCard/helpers.ts",
        "src/components/guest/modules/CheckInAccess.tsx",
        "src/components/guest/modules/WifiCard.tsx",
      ],
      thresholds: {
        lines: 70,
        functions: 70,
        branches: 60,
        statements: 70,
      },
    },
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
});



